
class argument_exception:
    pass
